name: Check if reviewer is assigned

on:
  pull_request_review:

jobs:
  check-reviewer:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/setup-python@v4
    - name: Write reviewer data
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        ACTOR_NAME: ${{ github.actor }}
      run: |
        cat <<EOF > reviewer_data.json
        {
          "advent": {
            "repos": ["syte-advent"],
            "reviewers": ["quassy", "JamesJoyce97"]
          }
        }
        EOF
    - name: Check if the PR has a reviewer
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        ACTOR_NAME: ${{ github.actor }}
      run: |
        python <<EOF
        import json
        import os
        repo_name = os.environ.get("REPO_NAME")
        actor_name = os.environ.get("ACTOR_NAME")
        with open('reviewer_data.json') as f:
            groups = json.load(f)
        print(f"Checking if {actor_name} is a reviewer for {repo_name}")
        for group_name, definitions in groups.items():
            print(f"Checking group {group_name}")
            if not repo_name in definitions["repos"]:
                print(f"Repo {repo_name} not found in group {group_name}")
                continue
            if actor_name in definitions["reviewers"]:
                print(f"Found reviewer {actor_name} in group {group_name} for repo {repo_name}")
                exit(0)
        else:
            print(f"{actor_name} is not a reviewer for {repo_name}")
            exit(1)
        EOF
