name: pre-commit

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
      name: Formatting Check
      id: format
      continue-on-error: true
      with:
        extra_args: --hook-stage pre-commit --from-ref HEAD~ --to-ref HEAD
    - uses: pre-commit/action@v3.0.1
      name: Linting Check (may fail)
      id: lint
      continue-on-error: true
      with:
        extra_args: --hook-stage manual --from-ref HEAD~ --to-ref HEAD
    - name: Check failures
      if: steps.format.outcome != 'success'  # || steps.tests.outcome != 'success'
      run: >
        echo "::error::Code not well formatted, please fix!  Passing this step is required, see section 'Formatting Check'
        in GitHub Action run to see formatting errors."
        && exit 1
