name: Is PR review actor data or Sven?

on:
  pull_request_review:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-24.04
    steps:
    - name: Check if Actor is a Member of one of the teams
      uses: im-open/is-actor-team-member@v1.2.0
      with:
        github-actor: ${{ github.actor }}
        github-organization: syte-tech
        github-team-slugs: |
          [
            "data-engineering",
          ]
        github-usernames: |
          [
            "jamesjoyce92"
          ]
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy the Code
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example, you might run a script or use a deployment tool
        echo "Deployment complete."
